default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: stratigos

development:
  <<: *default
  database: fellowshipfactory_dev

test:
  <<: *default
  database: fellowshipfactory_test

production:
  <<: *default
  database: fellowshipfactory_dev_production
  password: <%= ENV["FELLOWSHIPFACTORY_PROD_DATABASE_USERNAME"] %>
  username: <%= ENV["FELLOWSHIP_PROD_DATABASE_USERNAME"]

# ORIGINAL CONTENT FROM RAILS 8.1 CHECKOUT
#
# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
# production:
#   primary:
#     <<: *default
#     database: storage/production.sqlite3
#   cache:
#     <<: *default
#     database: storage/production_cache.sqlite3
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *default
#     database: storage/production_queue.sqlite3
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *default
#     database: storage/production_cable.sqlite3
#     migrations_paths: db/cable_migrate
